### ISSUE TITLE
Sub-unit feature for task forces, squads, shifts

### ISSUE THREAD

**Issue by kenoshabrickk** [openoversightva/openoversight#102]
It would be cool to have the ability to track particular units, assignments, task forces, and teams within a police department both to identify officers and to track the frequency of incidents perpetrated by each unit.

Ex. Data (which we currently can't import with all its complexity)
![image](https://github.com/openoversightva/openoversight/assets/118392825/c22d25cc-8731-4828-b987-3da92dd48c94)

**Comment by kfinity** [comment]
You know, this is an interesting question, and an important feature request. We're basically talking about the hierarchical organizational structure (e.g. here's [the RPD org chart](https://rva.gov/sites/default/files/2019-12/RPDOrgChart_0.pdf)).

There's 2 main ways I've seen this kind of data architecture done.

1. Flat/static - this is basically the way it shows up in the spreadsheet above. In the database, each assignment would have a separate field for Service, Division, Unit, and Team.
Pros: Easy to query data; easier to write code in the short term.
Cons: Rigid - every agency is expected to have the same number of levels to their org hierarchy. Also the hierarchy isn't enforced, so a user could add nonsensical assignments like "Business Services, Major Crimes, Sector 313, Recruit". Often ends up with awkward workarounds and messy in the long term.
2. Flexible/hierarchical - In this style, each assignment has one "org unit" (OU). The org unit can have 1 parent and 0+ child org units. So "3rd Precinct" would have a parent of "Patrol Services" probably, and child orgs of Sector 311, 312, 313 (and FMT?). In spreadsheet terms, the spreadsheet above would have one "unit" column, but you'd have to switch to a different sheet to see whether that unit was a service/division/unit/team/etc, and where it fit into the org chart hierarchy.
Pros: Once the hierarchy is set up for each agency, it's easy to create an assignment without mistakes (e.g. you could just pick Sector 412-NTAE and it would fill in the rest). It allows for each agency to have a very different org structure. If you have complex org structures, the code is easier in the long term.
Cons: More work in the short term to code it and define each agency's hierarchy. Harder to do certain queries.

Our current structure is static - each assignment has an Agency/Department and a Unit, and we have to figure out how to fit the data into those fields (which results in some awkward choices). 
Since our agencies often have very different structures (eg [VSP org chart](https://www.commonwealth.virginia.gov/media/governorvirginiagov/secretary-of-the-commonwealth/pdf/org-charts/state-police-org-chart-2016.pdf), [Fairfax PD org chart](https://www.fairfaxcounty.gov/police/sites/police/files/assets/generalorders/go-organizationalchart.pdf)), I would rather do the extra work of setting up org hierarchies than just add more fields and end up with even messier data in the future.

**Comment by kfinity** [comment]
In the short term, I think the best workaround for this would be to combine all the OU columns into one Unit description with standard delimiters (a dash or ">" or something). So in the above spreadsheet:

Adams could have Unit: "Special Investigations - Special Victims Unit"
Aeschlimann could have Unit: "4th Precinct - Sector 411 - NTAE"
etc

This will make data entry annoying bc the Units dropdown is already a hot mess for a lot of departments.

**Comment by kenoshabrickk** [comment]
Thank you so much for explaining how that works :) That's really interesting.

That's a good solution for the short-term. Just a daydream if we ever decide to move in that direction.

Also, you can always explain these things to me if you want. I am genuinely interested in understanding how the database works (and also what is possible). Thank you, Kevin.
