### ISSUE TITLE
Add 'bulk expire' option to imports

### ISSUE THREAD

**Issue by kenoshabrickk** [openoversightva/openoversight#116]
## What issue are you seeing?
@kfinity when I load new rosters, old cops still appear on the force as active. It's making the data a little bit messy & also gonna be inaccurate. 
It'd be nice to have a way to differentiate who's no longer where so the rosters on the front end are current. Idk if this is a Bryan task or a you one or one I can be taught and do myself, but would be a great priority before we import a ton.

**Comment by kfinity** [comment]
Yeah, so what needs to happen is that when we import a full, authoritative roster for a department, any assignments for officers who aren't on that list need to be ended (have an end date in the past, e.g. yesterday). You can manually edit and end the assignments through the UI, but it's a lot of work to do thousands of times.

Short term, I'll work on a database statement to bulk expire those officers, for departments we've already loaded through the import page. Previous departments I don't have an easy way to do that with, but we'll eventually overwrite them so that's fine.

Long term, I want to add a checkbox to the import page which says "this is an authoritative import, please end all old assignments in this department after importing". And then have it run the db statement to do that.

We'll need to have a checkbox, because when we get a redacted roster (e.g. Cfield), we can't assume that any missing officers are expired; they might be redacted.

**Comment by kfinity** [comment]
@kenoshabrickk I added a checkbox on the last import page to do this (the "bulk expire" question). It will only work if the roster sheet just has ONE department on it. Please test it out the next time you import a full authoritative roster for a department (which I think are most of them), and let me know here how it went.

**Comment by kenoshabrickk** [comment]
thank you so much, Kevin!
